### ISSUE TITLE
DesigningNETsolutionsForDocker.pdf cannot be loaded

### ISSUE THREAD

**Issue by itaign** [alexthissen/dockerworkshop2017#1]
Hi Alex,

It seems that this pdf file is corrupted.
Can you please re-load it?

Thanks,
Itai

**Comment by alexthissen** [comment]
Hi, Checked the original file and tried to view the file from the GitHub viewer as well. Both seem to be in order. Are you still experiencing this problem?
Alex

**Comment by itaign** [comment]
Perfect. Thanks.
